--- 
- hosts: localhost
  connection: local
  tasks:
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "DemoNewKeyPair"
      instance_type: t2.micro
      security_group: launch-wizard-15
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - { image: "ami-0fd05997b4dff7aac" , name: "manage-node-4" }
      - { image: "ami-053b12d3152c0cc71" , name: "manage-node-5" }
      - { image: "ami-053b12d3152c0cc71" , name: "manage-node-6" }
