---
- name: Enforce s3 bucket versioning on AWS account
  hosts: all
  gather_facts: false

  tasks:
    - name: List s3 bucket in AWS account
      amazon.aws.s3_bucket_info:
      register: result

    - debug:
        var: result

    - name: Enable versioning on S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: yes
      loop: "{{ result.buckets }}"
